### ISSUE TITLE
Docker Image 2.1 GB

### ISSUE THREAD

**Issue by Flightliner380** [mikenye/docker-ModeSMixer2#13]
Hello
I think there is an error in the DockerFile (currently the size is 2.1GB).In the Docker Buildfile, is the compiling of readsb and telegraf Agent, I think mm2 didn't need both inside the container.

**Comment by mikenye** [comment]
Yep, this is far too big. Let me see what I can do to reduce the size. `readsb` and `telegraf` were added for a specific user's requirements, however they shouldn't be adding that much size... My apologies, I will fix this ASAP.

**Comment by mikenye** [comment]
Found the culprit:

```
root@979cc0472a6b:~# du -hs /root/go
1.6G    /root/go
```

Thanks Go...

**Comment by mikenye** [comment]
I've made the decision to remove readsb/telegraf from this container. I will work with the other user regarding their use case, about building these into a new container using this container as a base.

Even after cleaning up after Go, the telegraf binary adds ~100MB to the image, which I'm not keen on.

**Comment by mikenye** [comment]
```
$ docker image ls mm2
REPOSITORY   TAG       IMAGE ID       CREATED              SIZE
mm2          latest    51a4bee8d7b3   About a minute ago   108MB
```

**Comment by mikenye** [comment]
This should now be resolved.
